import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  bgDark: {
    flex: 1,
    backgroundColor: '#18192a',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  headerContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 0,
    marginTop: 0,
  },
  logo: {
    width: 300,
    height: 100,
    marginTop: 40,
    marginBottom: 0,
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#fff',
    marginTop: 8,
    marginBottom: 4,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: 15,
    color: '#b0b0b0',
    marginBottom: 24,
    textAlign: 'center',
    paddingHorizontal: 24,
  },
  cardNew: {
    width: '94%',
    maxWidth: 420,
    backgroundColor: '#fff',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 18,
    paddingBottom: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.13,
    shadowRadius: 18,
    elevation: 10,
    alignItems: 'stretch',
    marginTop: 0,
    marginBottom: 8,
    alignSelf: 'center',
    minHeight: 420,
  },
  tabSwitcher: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
    marginBottom: 22,
    overflow: 'hidden',
    height: 48,
  },
  tab: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  tabActive: {
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  tabText: {
    color: '#888',
    fontWeight: '600',
    fontSize: 17,
  },
  tabTextActive: {
    color: '#3578e5',
    fontWeight: 'bold',
    fontSize: 17,
  },
  label: {
    fontSize: 15,
    color: '#555',
    marginBottom: 6,
    marginTop: 10,
    fontWeight: '500',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    marginBottom: 14,
    paddingHorizontal: 14,
    height: 48,
  },
  inputNew: {
    flex: 1,
    height: 48,
    color: '#222',
    fontSize: 17,
  },
  eyeIcon: {
    fontSize: 22,
    color: '#888',
    padding: 8,
  },
  loginButton: {
    backgroundColor: '#3578e5',
    borderRadius: 10,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 18,
    width: '100%',
    alignSelf: 'center',
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 19,
    fontWeight: 'bold',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 14,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e0e0e0',
  },
  orText: {
    color: '#888',
    fontSize: 15,
    marginHorizontal: 12,
    textAlign: 'center',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
  },
  footerText: {
    fontSize: 15,
    color: '#888',
    marginRight: 4,
  },
  link: {
    fontWeight: '600',
    fontSize: 15,
    color: '#5d3fd3',
  },
  signUpSpacing: {
    marginTop: 0,
  },
  socialRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  socialBtnFull: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 0,
    justifyContent: 'center',
    width: '48%',
  },
  socialIconFull: {
    width: 22,
    height: 22,
    marginRight: 12,
  },
  socialBtnText: {
    fontSize: 16,
    color: '#222',
    fontWeight: '500',
  },
});

export default styles;